### ISSUE TITLE
Fix issue in codacy

### ISSUE THREAD

**Issue by vietvo361** [minhphien/kmshcdc-patient-checking#52]

**Comment by harryul** [comment]
Clear all medium issues in codacy branch sandbox
Link: https://app.codacy.com/gh/minhphien/kmshcdc-patient-checking/issues?bid=24922503&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJXYXJuaW5nIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbXX1d
